Trombinoscoop/Trombinoscoop/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include



urlpatterns = (
	path('admin/', admin.site.urls),
    path('', include('Trombo.urls', namespace='trombo')),
   
    
)

Trombinoscoop/Trombo/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from .views import welcome,login,register, add_friend ,show_profile,modify_profile,ajax_check_email_field,ajax_add_friend  

app_name = 'trombo'

urlpatterns = (
    path('welcome',welcome, name='welcome'),
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('add_friend', add_friend, name='add_friend'),
    path('show_profile', show_profile, name='show_profile'),   
    path('modify_profile',modify_profile, name='modify_profile'),   
    path('ajax-checkEmailField',ajax_check_email_field, name='ajax_check_email_field'),  #validation de la creation d'un compte via ajax 
    path('ajax-addFriend', ajax_add_friend, name='ajax_add_friend')
)

'''configuration interface d'administration
username:admin
password:santibaniez
email:admin@demo.com
'''

Trombinoscoop/Trombo/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.conf import settings

class Faculte(models.Model) : 
	nom= models.CharField(max_length=30) 
	couleur = models.CharField(max_length=6) 

def __str__(self):
    return self.nom


class Personne(models.Model) : 
	nom= models.CharField(max_length=30) 
	prenom = models.CharField(max_length=30) 
	date_de_naissance = models.DateField() 
	matricule = models.CharField(max_length=10) 
	courriel = models.EmailField() 
	tel_fixe = models.CharField(max_length=20) 
	tel_mobile = models.CharField(max_length=20) 
	mot_de_passe = models.CharField(max_length=32)
	amis = models.ManyToManyField("self", null=True)
	faculte = models.ForeignKey(Faculte,on_delete=models.CASCADE)
	# Autres champs 
	type_de_personne = 'generic'  

def __str__(self):
    return self.prenom +" " +self.nom 


class Message(models.Model) : 
	auteur = models.ForeignKey(Personne ,on_delete=models.CASCADE)
	contenu = models.TextField() 
	date_de_publication = models.DateField() 

	def __str__(self) : 
		if len(self .contenu) > 20: 
			return self.contenu[:19] + "..."
		else: 
			return self.contenu 



class Campus(models.Model): 
	nom = models.CharField(max_length=30) 
	adresse_postale = models.CharField(max_length=60) 

def __str__(self):
    return self.nom

class Fonction(models.Model): 
	intitule = models.CharField(max_length=30)

def __str__(self):
    return self.intitule

class Cursus(models.Model) : 
	intitule = models.CharField(max_length=30) 

def __str__(self):
    return self.intitule


class Employe(Personne): 
	bureau = models.CharField(max_length=30) 
	campus = models.ForeignKey(Campus,on_delete=models.CASCADE) 
	fonction= models .ForeignKey(Fonction,on_delete=models.CASCADE)
	# Autres champs
	type_de_personne = 'employee'  


class Etudiant(Personne): 
	cursus = models.ForeignKey(Cursus,on_delete=models.CASCADE)
	# Autres champs 
	annee = models.IntegerField()
	type_de_personne = 'student' 
 

Trombinoscoop/Trombo/forms.py
from django import forms
from .models import Personne ,Etudiant,Employe

class LoginForm(forms.Form) : 
 email = forms.EmailField(label='Courriel ') 
 passwd= forms.CharField(label='Mot de passe',widget=forms.PasswordInput)

 def clean(self): 
  cleaned_data = super(LoginForm, self).clean() 
  email = cleaned_data.get("email") 
  password = cleaned_data.get("password") 

  if email and password: 
 	 result = Personne.objects.filter(mot_de_passe=password,courriel=email)

 	 if len(result) != 1: 
 	 	raise forms.ValidationError("Adresse de courriel ou mot de passe erroné(e). ")  
  return cleaned_data




class StudentProfileForm(forms.ModelForm) : 

	class Meta: 
		model = Etudiant 
		exclude = ('amis',) 




class EmployeeProfileForm(forms.ModelForm): 
	class Meta: 
		model = Employe 
		exclude = ('amis',) 



class AddFriendForm(forms.Form) : 
	email = forms.EmailField(label='Courriel : ') 

def clean(self) : 
  cleaned_data = super(AddFriendForm, self).clean() 
  email = cleaned_data.get("email")

    #Vérifie que le champ est valide 
  if email : 
    result = Personne.objects.filter(courriel=email) 
    if len(result) != 1: 
     raise forms .ValidationError("Adresse de courriel erronée.")
     return cleaned_data 

Trombinoscoop/Trombo/views.py
from django.shortcuts import render
from django import forms
from django.core.exceptions import ValidationError 

# Create your views here.

from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect,  HttpResponse 

from .forms import LoginForm,  StudentProfileForm , EmployeeProfileForm,AddFriendForm
from .models import Personne,Etudiant,Employe,Message 


def welcome(request):
	
  logged_user = get_logged_user_from_request(request) 
  if not logged_user is None : 
    if 'newMessage' in request.GET and request.GET['newMessage'] != '':
		   newMessage = Message(auteur=logged_user, contenu=request.GET['newMessage'], date_de_publication = datetime.date.today()) 
		   newMessage.save() 
    friendMessages = Message.objects.filter(auteur=logged_user).order_by('-date_de_publication') 
    return render(request,'welcome.html',{'logged_user' :logged_user,'friendMessages' :friendMessages})
  else: 
      return HttpResponseRedirect('/login') 




def login(request): 

	if request.method=="POST":
		form = LoginForm(request.POST or None) 
		if form.is_valid():
			user_email = form.cleaned_data['email']
			logged_user = Personne.objects.get(courriel=user_email) 
			request.session['logged_user_id'] = logged_user.id #initialisation de la session

			return HttpResponseRedirect('/welcome') 
	else: 
		form = LoginForm() 
	
	return render(request,'login.html', {'form' : form}) 




def register(request): 
   if len(request.GET) > 0 and 'profileType' in request.GET: 

      studentForm = StudentProfileForm(prefix="st") 
      employeeForm = EmployeeProfileForm(prefix="em") 

      if request.GET['profileType'] == 'student': 
          studentForm = StudentProfileForm(request.GET, prefix="st") 
          if studentForm.is_valid() : 
             studentForm.save(commit=True) 
             return HttpResponseRedirect('/login') 

      elif request.GET['profilelype'] == 'employee' : 
           employeeForm = EmployeeProfileForm(request.GET, prefix="em") 
           if employeeForm.is_valid(): 
              employeeForm.save(commit=True) 
              return HttpResponseRedirect('/login') 

              #Le formulaire envoyé n'est pas valide 
      return render(request,'user_profile.html ' ,{'studentForm' : studentForm, 'employeeForm': employeeForm}) 
   else: 
     
       studentForm = StudentProfileForm(prefix="st") 
       employeeForm = EmployeeProfileForm(prefix="em") 
       return render(request,'user_profile.html ', {'studentForm': studentForm, 'employeeForm' : employeeForm}) 



def get_logged_user_from_request(request): 

     if 'logged_user_id' in request.session: 

        logged_user_id = request.session['logged_user_id'] 
           # On cherche un etudiant 

        if len(Etudiant.objects.filter(id=logged_user_id)) == 1: 
             return Etudiant.objects.get(id=logged_user_id) 
             # On cherche un Employe 

        elif len(Employe.objects.filter(id=logged_user_id)) == 1: 
             return Employe.objects.get(id=logged_user_id) 
             # Si on n'a rien trouve 
        else: 

      	     return None  
     else: 
      	return None      


def add_friend(request) : 

    logged_user = get_logged_user_from_request(request) 
    if logged_user: 
    #Teste si le formulaire a été envoyé 
      if len(request.GET) > 0: 
         form = AddFriendForm(request.GET) 

         if form.is_valid(): 
            new_friend_email = form.cleaned_data['email'] 
            newFriend = Personne.objects.get(courriel=new_friend_email) 
            logged_user.amis.add(newFriend) 
            logged_user.save() 
            return HttpResponseRedirect('/welcome') 

         else: 
          return render(request,'add_friend.html' , {'form' : form}) 
         #Le formulaire n'a pas été envoyé 
      else: 
        form = AddFriendForm() 
        return render(request,'add_friend.html', {'form' : form} ) 
    else: 
      return HttpResponseRedirect('/login')  




def show_profile(request): 

   logged_user = get_logged_user_from_request(request) 
   if logged_user: 
   # Teste si le paramètre attendu est bien passé 
    if 'userToShow' in request.GET and request.GET['userToShow'] != '':
      results = Personne.objects.filter(id=request.GET['userToShow']) 
      if len(results) == 1:

        if Etudiant.objects.filter(id=request.GET['userToShow']): 
           user_to_show = Etudiant.objects.get(id=request.GET['userToShow']) 
        else: 
           user_to_show = Employe.objects.get(id=request.GET['userToShow']) 
        return render(request,'show _profile.html',{'user_to_show' : user_to_show})

      else: 
        return render(request,'show _profile.html', {'user_to_show' : logged_user})
      # Le paramètre n'a pas été trouvé 
    else: 
      return render(request,'show _profile.html',{'user_to_show': logged_user}) 
   else: 
      return HttpResponseRedirect('/login') 



def modify_profile(request) : 

  logged_user = get_logged_user_from_request(request)

  if logged_user: 
    if len(request.GET) > 0: 
      if type(logged_user) == Etudiant:  
       form = StudentProfileForm(request.GET, instance=logged_user) 
      else: 
        form = EmployeeProfileForm(request.GET, instance=logged_user) 
      if form.is_valid(): 
        form.save(commit=True) 
        return HttpResponseRedirect('/welcome') 

      else: 
        return render(request,'modify _profile.html', {'form' : form}) 
    else: 
      if type(logged_user) == Etudiant: 
          form = StudentProfileForm(instance=logged_user) 
      else: 
        form = EmployeeProfileForm(instance=logged_user) 
      return render(request,'modify _profile.html', {'form' : form}) 
  else: 
    return HttpResponseRedirect('/login') 




def ajax_check_email_field(request): 

  HTML_to_return = ' '

  if 'value' in request.GET:

    field = forms .EmailField() 
    try: 
      field.clean(request.GET['value'])
    except ValidationError as ve:
      HTML_to_return = '<ul class="errorlist">'

      for message in ve.messages: 
        HTML_to_return += '<li>' + message + '</li>'

      HTML_to_return += '</ul>' 

  return HttpResponse(HTML_to_return)  






def ajax_add_friend(request):

  HTML_to_return = ' ' 
  logged_user = get_logged_user_from_request(request) 

  if not logged_user is None: 

    if 'email' in request.GET: 
      new_friend_email = request.GET['email'] 
      if len(Personne.objects.filter(courriel=new_friend_email)) == 1:
        new_friend = Personne.objects.get(courriel=new_friend_email) 
        logged_user.amis.add(new_friend) 
        logged_user.save()

      HTML_to_return = '<li><a href="show_profile?userToShow='
      HTML_to_return += str(new_friend.id) 
      HTML_to_return += '">' 
      HTML_to_return += new_friend.prenom + ' ' + new_friend.nom 
      HTML_to_return += '</a></li>' 

      return HttpResponse(HTML_to_return)   

Trombinoscoop/Trombo/templates/add_friend.html
{% extends "base.html" %} 
{% load  static %}

{% block title %}Ajout d'un ami{% endblock %}

{% block bodyid %}addUserPage{% endblock %}

{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/cssaddfriend.css' %}" />{% endblock %}

{% block content %} 
  <hl style="font:35px Monotype Corsiva;margin-top=40px;"><u>Ajout d'un ami</u></hl> 

  <form action="add_friend" method="get"> 
  	{{  form.as_p }} 
  	<p> <input type="submit" value="Ajouter" /> </p> 
  </form> 

  <!-- usage de ajax -->

  <Script type="text/javascript"> 
  	$(document).ready(function() { 
  	   $("#friendlist form").submit(addFriend);
  	 }) ; 
    
    function addFriend() { 
      $fieldValue = $("#newFriendlnput").val(); 

      $.ajax({ 
      url : 'ajax-addFriend', 
      data: ({email : $fieldValue}) ,
      type: 'GET', 
      success: function($data, $textStatus, $XMLHttpRequest) { 
      	// alert($data);
      	$('#friendlist ul').prepend($data); 
      } 

     });

    return false;  
</script> 

{% endblock %} 

Trombinoscoop/Trombo/templates/base.html
{% load  static %}

<html> 
<head> 
	<title>Trombinoscoop -{% block title%}{% endblock %} </title>
	
	   <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
	   <link rel="stylesheet" type="text/css" href="{% static 'css/cssfooter.css' %}" />
	   
	   <style>
	     nav{width:100%;height:; text-align:center; background-color:cornflowerblue;}
         nav ul{display:table;}
         nav ul li{float:left;list-style-type:none;}
         nav ul li:last-child{padding-right:0px; }
         nav ul li a{color:white;text-decoration: none; font-size:18px; padding: 20px 125px; display:inline-block; transition: all 0s ease 0s;}
         nav ul li a:hover{background-color:#002e5b; color:#fde428; transition: all 0.5s ease 0s;}
       </style>

	   {% block css %}{% endblock %}
		
	{% block js %}{% endblock %}

</head> 
<body id="{% block bodyid%} genericPage {% endblock %}">

    <header > 
	  <div>
         <img src="{% static 'img/logo.jpg' %}" width="100%">	  
	  </div>
	</header>
	
	<nav> 
	   <ul class="menu">
             <li><a href="welcome">Accueil</a></li>
             <li><a href="login">Login</a></li>
             <li><a href="register">Register</a></li>
             <li><a href="#">Log-Out</a></li>               
	   </ul>
	</nav>


	<section> 
	    {% block headerContent %}{% endblock %}
	</section>

	<Section id="content">
	    {% block content %} {% endblock %} 

	</section>

      <!-- blog pour publiciter -->

    <div class="publicite" style="margin-bottom:20px;">
		   <img src="{% static 'img/remise.gif' %}" alt="publicité" width="100%" height="60px"/>
	  </div>


 <!-- End of Contact Section -->

      <footer>
        <div class="wrapper">
          <div class="footer-container">
             <div class="footer-left">
                <img src="{% static 'img/logofooter.jpg' %}" alt=""  style="border-radius:50%;">
             </div>

             <div class="footer-center">
                <h4 class="list-title">Quick Links</h4>

                <ul>
                  <li>
                     <a href="welcome">Welcome</a>
                  </li>

                  <li>
                     <a href="add_friend">AddFriend</a>
                  </li>

                  <li>
                     <a href="show_profile">Show-Profile</a>
                  </li>

                  <li>
                    <a href="modify_profile">Modify Profile</a>
                  </li>
                </ul>
             </div>

            <div class="footer-right">
                <h4 class="list-title">Follow us on</h4>

                <div class="social-icons">
                   <a href="#">
                      <img src="{% static 'img/instagram-logo.png' %}" alt="" />
                   </a>

                   <a href="#">
                      <img src="{% static 'img/facebook-logo.png' %}" alt="" />
                   </a>

                   <a href="#">
                      <img src="{% static 'img/twitter-logo.png' %}" alt="" />
                   </a>
            </div>

            <p>This website is developed by fotso &copy; 2021</p>

          </div>
        </div>
      </footer>

     

    <script src="{% static 'js/jquery.min.js' %}"></script> 
  	
</body> 
</html> 

Trombinoscoop/Trombo/templates/login.html
{% extends 'base.html' %} 
{% load  static %}

{% block title %}Connexion{% endblock %}
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/csslogin.css' %}" />{% endblock %}


{% block bodyid %}loginPage{% endblock %}

{% block content %} 

   <form action="login" method="POST" id="log"> 
   	 {% csrf_token %}

   	 {{ form.as_p }}

     <P class="btn"> 
     	<input type="submit" value="Se connecter" /> <a href="????">Créer un compte</a> 
     </P> 
   </form> 
{% endblock %} 

Trombinoscoop/Trombo/templates/modify _profile.html
{% extends "base.html" %} 
{% load  static %}

{% block title %}Modification de mon profil{% endblock %} 
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/cssmodifyprof.css' %}" />{% endblock %}

{% block bodyld %}modifyProfilePage{% endblock %}

{% block content %} 
  <hl style="font:35px Monotype Corsiva;"><u>Modification de mon profil</u></hl> 
  <form action="modify_profile" method="get"> 
  	{{ form.as_p }} 

  	<p> 
  		<input type="submit" value="Modifier" /> 
  	</p> 
  </form> 
{% endblock %} 

Trombinoscoop/Trombo/templates/show _profile.html
{% extends "base.html" %} 
{% load  static %}

{% block title %}Affichage d'un profil{% endblock %} 
{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/csshowprofil.css' %}" />{% endblock %}

{% block bodyid %}showProfilePage{% endblock %}

{% block content %} 
  <hl style="font:35px Monotype Corsiva;"><u>Affichage d'un profil</u></hl> 
  <dl class="fieldlist"> 
  	 <dt>Nom :</dt> 
  	  <dd>{{ user_to_show.nom }}</dd> 
  	 <dt>Prénom :</dt> 
  	   <dd>{{ user_to_show.prenom }}</dd> 
  	 <dt>Date de naissance :</dt> 
  	    <dd>{{ user_to_show.date_de_naissance }}</dd> 
  	 <dt>Matricule :</dt> 
  	    <dd>{{ user_to_show.matricule }}</dd> 
  	 <dt>Courriel :</dt> 
  	    <dd>{{ user_to_show.courriel }}</dd> 
  	 <dt>Tél . fixe :</dt> 
  	    <dd>{{ user_to_show.tel_fixe }}</dd> 
  	 <dt>Tél . mobile :</dt> 
  	    <dd>{{ user_to_show.tel_mobile }}</dd> 
  	 <dt>Faculté :</dt> 
  	    <dd>{{ user_to_show.faculte.nom }}</dd> 
  	      {%if user_to_show.type_de_personne == "student" %} 

  	 <dt>Cursus :</dt> 
  	    <dd>{{ user_to_show.cursus.intitule }}</dd> 

  	 <dt>Année :</dt> 
  	    <dd>{{ user_to_show.annee }}</dd>
  	      {% elif user_to_show.type_de_personne == "employee" %} 
  	  <dt>Bureau :</dt> 
  	    <dd>{{ user_to_show.bureau }}</dd> 
  	  <dt>Campus :</dt> 
  	    <dd>{{ user_to_show.campus.nom }}</dd> 
  	  <dt>Fonction :</dt> 
  	    <dd>{{ user_to_show.fonction.intitule }}</dd> 
 
         {% endif %} 
   </dl> 
 <p id="showProfileNavigationBut tons"> 
 	<a href="welcome" class="buttonlink">Retour / Back</a> 
 </p> 

 {% endblock %} 

Trombinoscoop/Trombo/templates/user_profile.html
{% extends 'base.html' %} 
{% load  static %}

{%block title %}Création d' un profil{% endblock %}
 
{% block css %}
   <link rel="stylesheet" type="text/css" href="{% static 'css/cssuser_profile.css' %}" />
{% endblock %}

{% block bodyld %}userProfilePage{% endblock %}

{% block content %} 

  <!-- usage de ajax -->

  <Script type="text/javascript"> 
    $(document).ready(function()
      { 
        $("input #id_courriel").focusout(checkEmailField) ; 
      }); 
   
   function checkEmailField() { 
      alert('Courriel introduit . On va mai ntenant le valider. ');

      $fieldValue = $("input#id_courriel ").val();
      $.ajax({ 
  
       url : '/ajax/checkEmailField', 
       data: ({value : $fieldValue}) ,
       type: 'GET',
       success: function($data, $textStatus, $XMLHttpRequest) { 
         if ($data != '') { 
           // alert($data) ;
           $("input#id_courriel ").parent().prev('.errorlist').remove(); 
           $("input#id_courriel ").parent().before($data); 
         } 
       } 
      });  
   } 
  </script> 
  
  <form> 
  	<p> 
  		<label for="profileType" style="font:35px Monotype Corsiva;"><u>Vous êtes :</u></label> 

  		<select id="profileType" onchange="displayRightForm()">
  			<option value="student" {%if studentForm.is_bound %} selected="selected" {% endif %}>Étudiant</option> 
  			<option value="employee" {%if employeeForm.is_bound %} selected="selected" {% endif %}>Employé</option> 
  		</select> 
  	</p> 
  </form>


  <form action="register" method="get" id="studentForm"> 
  	{{ studentForm.as_p }} 

  	<p> 
  		<input type="hidden" name="profileType" value="student" /> 
  		<input type="submit" value="Créer un compte" /> 
  	</p> 
  </form> 
  
  <form action="register " method="get" id="employeeForm"> 
  	{{ employeeForm.as_p }} 

  	<p> 
  		<input type="hidden" name="profileType" value="employee" />
  		<input type="submit" value="Créer un compte" /> 
  	</p> 
  </form> 

{% endblock %} 

 
{% block js %} 

     <script type="text/javascript">

         function displayRightForm(){ 

           if ($('#profileType').val() == 'student') { 
             $('#employeeForm').hide(); 
             $('#studentForm').show(); 
           } else { 
             $('#studentForm').hide() ; 
             $('#employeeForm').show() ; 
           }
         } 
        
        $(document).ready(displayRightForm);
        $( '#profileType').change(displayRightForm); 

    </script>


{% endblock %} 

Trombinoscoop/Trombo/templates/welcome.html
{% extends 'base.html' %}
{% load  static %} 

{% block css %}<link rel="stylesheet" type="text/css" href="{% static 'css/styleWelcome.css' %}" />{% endblock %}

{% block headerContent %}

 

<p id="name"><marquee><i> Welcome Mr: {{ logged_user.prenom }} {{ logged_user.nom }} </i></marquee></p> 
<p id="name">Welcome Mr:{{ logged_user.prenom }} {{ logged_user.nom }} </p> 
<p id="function"> 
   {%if logged_user.type_de_personne == 'student' %} 
    Étudiant en 
     {% if logged_user.annee == 1 %} 
       {{ logged_user.annee }}ère 
     {% else %} 
       {{ logged_user.annee }}ème 
     {% endif %} 
     {{ logged_user.cursus.intitule }} 
   {% else %} 
      {{ logged_user.fonction.intitulelcapfirst }} dans la faculté 
        {{ logged_user.faculte }} 
   {% endif %} 
</p> 

<p id="profilelinks"> 
	<a href="show_profile?userToShow={{ logged_user.id }}" class="buttonlink">Voir le profil</a> 
    <a href="modify_profile" class="buttonlink">Modifier le profil</a> 
</p> 

{% endblock %} 

{% block content %} 
   <section id="messagelist">
   	  <form action="welcome" method="get" class="inlineForm"> 
   	  	 <label class="newMessagelnput" for="newMessagelnput">Publier un message :</label> 
   	  	 <input type="text" name="newMessage" id="newMessagelnput" /> 
   	  	 <input type="submit" value="Publier" /> 
   	  </form> 

   	  <ul> 
   	  	{% for message in friendMessages %} 

   	  	 <li> <p> <a href="show_profile?userToShow={{ message.auteur.id }}">{{ message.auteur.prenom}} {{message.auteur.nom }}</a> dit : </p> 
   	  	 	  <p>{{ message.contenu }}</p> 
   	  	 </li> 
   	  	{% endfor %} 
   	  </ul> 
   
   </section> 
   <section id="friendlist">
   	 {# <p class="title">Ajout des ami(e)s</p>  #}

     <!-- ajouter des amis via ajax -->
       <form action="welcome" method="get" class="inlineForm">
         <label class="newMessagelnput" for="newFriendinput">Ajout des ami(e)s:</label> 	   
         <input type="email" name="newFriend" id="newFriendinput" placeholder="Entrez son Courriel" /> 
         <input type="submit" value="Ajouter" />
       </form>  
     <!-- ajouter des amis via ajax -->
     
     
   	 <p><a href="add_friend" class="buttonlinkAdd">Ajouter via ce lien</a></p> 
	 
	 <p class="title" style="font:35px Monotype Corsiva;"><u>Liste de Mes amis: </u></p> 
   	 <ul  style="list-style-type:none;">  
   	 	{% for ami in logged_user.amis.all %} 
   	 	  <li><a href="show_profile?userToShow={{ ami.id}}">{{ ami.prenom}} {{ ami.nom }}</a></li> 
   	    {% endfor %} 
   	</ul> 

   </section> 
{% endblock %} 